openapi: 3.0.0
info:
  title: API for managing mahjong scores
  description: This API provides functionality for managing mahjong scores.
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /:
    get:
      summary: BE 起動確認用のエンドポイント
      responses:
        '200':
          description: BE 起動確認用のエンドポイント
          content:
            application/json:
              schema:
                type: string

  /api/v1/get-records:
    get:
      summary: 成績データの取得
      parameters:
        - in: query
          name: userId
          description: ユーザーID
          schema:
            type: string
          example: "PENgoeRqqWahTPhU3Y74"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  recordList:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "CxoqIFMJN6vg0I738Rtv30ZXWYzKWz"
                        rule:
                          type: string
                          example: "Mリーグルール"
                        date:
                          type: string
                          example: "2023/4/16 12:00"
                        score:
                          type: integer
                          example: 10000
                        gameType:
                          type: integer
                          example: 4
                        rank:
                          type: integer
                          example: 2
                      required:
                        - id
                        - rule
                        - date
                        - score
                        - gameType
                        - rank
                  rankData:
                    type: object
                    additionalProperties:
                      type: integer
                    example:
                      "1": 2
                      "2": 10
                      "3": 1
                      "4": 1

  /api/v1/add-record:
    post:
      summary: データの追加
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Record'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string

  /api/v1/add-user:
    post:
      summary: ユーザーの追加
      parameters:
        - in: query
          name: userId
          description: ユーザーID
          schema:
            type: string
          example: "AAAAAAAAAAaaaaaaaaaa1111111111"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Record:
      type: object
      properties:
        userId:
          type: string
          example: "PENgoeRqqWahTPhU3Y74"
        date:
          type: string
          format: date-time
          example: "2023/4/16 12:00"
        gameType:
          type: integer
          example: 4
        rank:
          type: integer
          example: 2
        rule:
          type: string
          example: "Mリーグルール"
        score:
          type: integer
          example: 10000
      required:
        - userId
        - date
        - gameType
        - rank
        - rule
        - score
