openapi: "3.0.3"

info:
  title: "API for Mahjong Score Manage"
  version: "1.0"

servers:
- url: "http://localhost:8000"
  description: "ローカル環境"

paths:
  /:
    get:
      summary: "BE 起動確認用のエンドポイント"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
